name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: cordiverse/workflows/.github/actions/setup@main

      - name: Get Datas
        run: |
          pwd
          npm pack koishi-plugin-pcr-landosol-roster
          tar -xzf koishi-plugin-pcr-landosol-roster-*.tgz \
          -C 'packages/landosol-roster/data' \
          'package/data/chara_name.json' \
          'package/data/chara_profile.json' \
          'package/data/unavailable_chara.json'
          ls -alF package/data

      - name: Get Hash
        id: current-hash
        run: |
          echo "chara_name=$(sha256sum packages/landosol-roster/data/chara_name.json | awk '{print $1}')" >> $GITHUB_OUTPUT
          echo "chara_profile=$(sha256sum packages/landosol-roster/data/chara_profile.json | awk '{print $1}')" >> $GITHUB_OUTPUT
          echo "unavailable_chara=$(sha256sum packages/landosol-roster/data/unavailable_chara.json | awk '{print $1}')" >> $GITHUB_OUTPUT

      # - name: Create Folder
      #   run: mkdir LandosolRoster

      # - name: Get Landosol Roster Data
      #   uses: actions/checkout@v4
      #   with:
      #     repository: 'Ice9Coffee/LandosolRoster'
      #     path: 'LandosolRoster'

      # - name: Get Landosol Roster Data Hash
      #   run: ls -alF LandosolRoster
  #     - name: Build
  #       run: |
  #         (yarn build 2>&1) | tee build.log
  #         exit ${PIPESTATUS[0]}

  #     - name: Create Result Markdown
  #       if: ${{ success() || failure() }}
  #       run: |
  #         tee -a output.md <<EOF
  #         ### Build $([ "${{ job.status }}" = 'success' ] && echo "✅" || echo "❌")

  #         <details>
  #           <summary>Details</summary>

  #           \`\`\`shell
  #           $(cat build.log)
  #           \`\`\`
  #         </details>

  #         EOF

  #     - name: Upload Build Log
  #       if: ${{ success() || failure() }}
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: build-log
  #         path: output.md
  # publish:
  #   uses: cordiverse/workflows/.github/workflows/publish.yml@main
  #   secrets:
  #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
