name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: cordiverse/workflows/.github/actions/setup@main

      - name: Check File Changes
        id: check-changes
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          FILE_CHANGES=$(git diff-tree --no-commit-id --name-only -r $COMMIT_ID | grep 'packages/landosol-roster/package.json')
          if [ -z "$FILE_CHANGES" ]; then
            echo "File changes not found."
            echo "file_changed=false" >> $GITHUB_OUTPUT
          else
            echo "File changes found."
            echo "file_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Get Datas
        if: steps.check-changes.outputs.file_changed
        run: |
          npm pack koishi-plugin-pcr-landosol-roster
          tar -zxvf koishi-plugin-pcr-landosol-roster-*.tgz \
          -C 'packages/landosol-roster/data' \
          --strip-components=2 \
          'package/data/chara_name.json' \
          'package/data/chara_profile.json' \
          'package/data/unavailable_chara.json'
          ls -alF packages/landosol-roster/data

      - name: Get Hash
        if: steps.check-changes.outputs.file_changed
        id: current-hash
        run: |
          echo "chara_name=$(sha256sum packages/landosol-roster/data/chara_name.json | awk '{print $1}')" >> $GITHUB_OUTPUT
          echo "chara_profile=$(sha256sum packages/landosol-roster/data/chara_profile.json | awk '{print $1}')" >> $GITHUB_OUTPUT
          echo "unavailable_chara=$(sha256sum packages/landosol-roster/data/unavailable_chara.json | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Create Folder
        if: steps.check-changes.outputs.file_changed
        run: mkdir LandosolRoster

      - name: Get Landosol Roster Data
        if: steps.check-changes.outputs.file_changed
        uses: actions/checkout@v4
        with:
          repository: 'Ice9Coffee/LandosolRoster'
          path: 'LandosolRoster'

      - name: Get Landosol Roster Data Hash
        if: steps.check-changes.outputs.file_changed
        id: remote-hash
        run: |
          echo "chara_name=$(sha256sum LandosolRoster/chara_name.json | awk '{print $1}')" >> $GITHUB_OUTPUT
          echo "chara_profile=$(sha256sum LandosolRoster/chara_profile.json | awk '{print $1}')" >> $GITHUB_OUTPUT
          echo "unavailable_chara=$(sha256sum LandosolRoster/unavailable_chara.json | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: CAS Chara Name
        if: steps.check-changes.outputs.file_changed && steps.current-hash.outputs.chara_name != steps.remote-hash.outputs.chara_name
        run: cp LandosolRoster/chara_name.json packages/landosol-roster/data/chara_name.json

      - name: CAS Chara Profile
        if: steps.check-changes.outputs.file_changed && steps.current-hash.outputs.chara_profile != steps.remote-hash.outputs.chara_profile
        run: cp LandosolRoster/chara_profile.json packages/landosol-roster/data/chara_profile.json

      - name: CAS Unavailable Name
        if: steps.check-changes.outputs.file_changed && steps.current-hash.outputs.unavailable_name != steps.remote-hash.outputs.unavailable_name
        run: cp LandosolRoster/unavailable_name.json packages/landosol-roster/data/unavailable_name.json

      - name: Build
        run: |
          (yarn build 2>&1) | tee build.log
          exit ${PIPESTATUS[0]}

      - name: Create Result Markdown
        if: ${{ success() || failure() }}
        run: |
          tee -a output.md <<EOF
          ### Build $([ "${{ job.status }}" = 'success' ] && echo "✅" || echo "❌")

          <details>
            <summary>Details</summary>

            \`\`\`shell
            $(cat build.log)
            \`\`\`
          </details>

          EOF

      - name: Upload Build Log
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: output.md
          
  publish:
    uses: cordiverse/workflows/.github/workflows/publish.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
